/**
 * Super API Documentation
 * The Super API makes superannuation fund data easily accessible for developers.  Build the future.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@superapi.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The APIEntitiesPerformance model module.
 * @module model/APIEntitiesPerformance
 * @version 1.0.0
 */
class APIEntitiesPerformance {
    /**
     * Constructs a new <code>APIEntitiesPerformance</code>.
     * The performance for a superannuation FundOption on a specific day.  Not all FundOptions will have a performance on every day, as some FundOptions are not relevant on every day (ie: public holidays, weekends, market closures, etc).  A result of 0 represents no performance.
     * @alias module:model/APIEntitiesPerformance
     * @param report {String} Type of performance report
     * @param _date {Date} Date of the performance period
     * @param growthRate {Number} Growth rate for the performance period
     * @param growthRateType {String} Identifies how the growth rate should be interpreted, ie: as a percentage.  Currently only percentage is used.  Other options may become available in the future.
     */
    constructor(report, _date, growthRate, growthRateType) { 
        
        APIEntitiesPerformance.initialize(this, report, _date, growthRate, growthRateType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, report, _date, growthRate, growthRateType) { 
        obj['report'] = report;
        obj['date'] = _date;
        obj['growth_rate'] = growthRate;
        obj['growth_rate_type'] = growthRateType;
    }

    /**
     * Constructs a <code>APIEntitiesPerformance</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/APIEntitiesPerformance} obj Optional instance to populate.
     * @return {module:model/APIEntitiesPerformance} The populated <code>APIEntitiesPerformance</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new APIEntitiesPerformance();

            if (data.hasOwnProperty('report')) {
                obj['report'] = ApiClient.convertToType(data['report'], 'String');
            }
            if (data.hasOwnProperty('date')) {
                obj['date'] = ApiClient.convertToType(data['date'], 'Date');
            }
            if (data.hasOwnProperty('growth_rate')) {
                obj['growth_rate'] = ApiClient.convertToType(data['growth_rate'], 'Number');
            }
            if (data.hasOwnProperty('growth_rate_type')) {
                obj['growth_rate_type'] = ApiClient.convertToType(data['growth_rate_type'], 'String');
            }
        }
        return obj;
    }


}

/**
 * Type of performance report
 * @member {String} report
 */
APIEntitiesPerformance.prototype['report'] = undefined;

/**
 * Date of the performance period
 * @member {Date} date
 */
APIEntitiesPerformance.prototype['date'] = undefined;

/**
 * Growth rate for the performance period
 * @member {Number} growth_rate
 */
APIEntitiesPerformance.prototype['growth_rate'] = undefined;

/**
 * Identifies how the growth rate should be interpreted, ie: as a percentage.  Currently only percentage is used.  Other options may become available in the future.
 * @member {String} growth_rate_type
 */
APIEntitiesPerformance.prototype['growth_rate_type'] = undefined;






export default APIEntitiesPerformance;

