/**
 * Super API Documentation
 * The Super API makes superannuation fund data easily accessible for developers.  Build the future.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@superapi.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SuperApiDocumentation);
  }
}(this, function(expect, SuperApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('APIEntitiesCumulativePerformance', function() {
    it('should create an instance of APIEntitiesCumulativePerformance', function() {
      // uncomment below and update the code to test APIEntitiesCumulativePerformance
      //var instane = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be.a(SuperApiDocumentation.APIEntitiesCumulativePerformance);
    });

    it('should have the property report (base name: "report")', function() {
      // uncomment below and update the code to test the property report
      //var instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be();
    });

    it('should have the property growthRate (base name: "growth_rate")', function() {
      // uncomment below and update the code to test the property growthRate
      //var instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be();
    });

    it('should have the property growthRateType (base name: "growth_rate_type")', function() {
      // uncomment below and update the code to test the property growthRateType
      //var instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "start_date")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "end_date")', function() {
      // uncomment below and update the code to test the property endDate
      //var instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be();
    });

    it('should have the property cumulativeDates (base name: "cumulative_dates")', function() {
      // uncomment below and update the code to test the property cumulativeDates
      //var instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be();
    });

    it('should have the property performanceDates (base name: "performance_dates")', function() {
      // uncomment below and update the code to test the property performanceDates
      //var instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be();
    });

    it('should have the property nonPerformanceDates (base name: "non_performance_dates")', function() {
      // uncomment below and update the code to test the property nonPerformanceDates
      //var instance = new SuperApiDocumentation.APIEntitiesCumulativePerformance();
      //expect(instance).to.be();
    });

  });

}));
