/**
 * Super API Documentation
 * The Super API makes superannuation fund data easily accessible for developers.  Build the future.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@superapi.com.au
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SuperApiDocumentation);
  }
}(this, function(expect, SuperApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SuperApiDocumentation.PerformanceApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PerformanceApi', function() {
    describe('getV1NameAnnual', function() {
      it('should call getV1NameAnnual successfully', function(done) {
        //uncomment below and update the code to test getV1NameAnnual
        //instance.getV1NameAnnual(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1NameCumulative', function() {
      it('should call getV1NameCumulative successfully', function(done) {
        //uncomment below and update the code to test getV1NameCumulative
        //instance.getV1NameCumulative(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1NameDaily', function() {
      it('should call getV1NameDaily successfully', function(done) {
        //uncomment below and update the code to test getV1NameDaily
        //instance.getV1NameDaily(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1NameDailyLatest', function() {
      it('should call getV1NameDailyLatest successfully', function(done) {
        //uncomment below and update the code to test getV1NameDailyLatest
        //instance.getV1NameDailyLatest(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1NameDailyToday', function() {
      it('should call getV1NameDailyToday successfully', function(done) {
        //uncomment below and update the code to test getV1NameDailyToday
        //instance.getV1NameDailyToday(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getV1NameDailyYesterday', function() {
      it('should call getV1NameDailyYesterday successfully', function(done) {
        //uncomment below and update the code to test getV1NameDailyYesterday
        //instance.getV1NameDailyYesterday(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
